language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - d.rubio@outlook.com
# services:
# - mysql
# - mongodb
# before_install:
# - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report install -Dmaven.test.failure.ignore=false

  #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=daniel-nx -Dsonar.login=$SONAR