language: java
branches:
  only:
  - develop
  - "/^release-[0-999].[0-999]$/"
  - master
notifications:
  email:
    recipients:
    - d.rubio@outlook.com
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=daniel-nx
  -Dsonar.login=$SONAR
deploy:
  provider: heroku
  on:
    branch: master
  app: nx-ecosystem-template
  api_key:
    secure: vWjezdAlsbN/F98fl88KyiFd1fKdGGUEicSNEMOBDFHHswLKcBQ6zEVvHxsAWmTVEOSa997kAd+dvFHjzk3nVhYarpopxCcmaZ9TLMICooC4Hu0PmSG5lpLNr2Ra6rzpd5q1MS11M+oaH9on0URbXy9F4UbEGFpSZrOXUGzwNHsPsz/IEMy57oXMxzc/kf4/GNkjZ5kmU5ZzV5zaqZT/qiehn2wl2Qh1bLd8A4SgtjXu6B/det4Uzhqk5X5akqadSwqZG+b+P7jkUjLlE7O8pnRx57HIK5B/rpznrYs2qHV8F6YZ/UMIg5z1u9YNqV4mGZc+R6E6hV4GeUdBbQXXTi9JP6l+yb/OUuSQRIXhWPFmIA1Zj0VWqjbBg79Js4haZe4X8SzQe2rYFqxgWyVEyFk4P3xS42WxtawuBKdE+mSij71/8xuqY3euLBFoAUFy8Kg5F1S4Ko8OLqY0XvIAyK9An5s3dFG3WMc93PrXfjpRga6Db3nmUt5uGuUcHmOQmBFdxgo3W4KjUEyiMlA70d3HomjnnJd69eueE0nMvRRE55b6orzQO3LsPapqp+hXcd0/P+f1QN+bE4I4uF9xh5SJEzJtHBSOFcc3mthoXgbgQ0vktVEvvl/DJzIhltUvyENOS5zLWwSHYppdFXU+GpoQbUjuQ/5IL2EE9i5K5sI=
