language: java
branches:
  only:
  - develop
  - "/^release-[0-999].[0-999]$/"
  - master
notifications:
  email:
    recipients:
    - d.rubio@outlook.com
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=daniel-nx
  -Dsonar.login=$SONAR
deploy:
  provider: heroku
  on:
    branch: master
  app: nx-ecosystem-template
  api_key:
    secure: hllyBFVkG0fhmb5QP1KYGmxXf2HCG92Qnl+mvhATA8tANiBOI1dQgGqRDs6zDfeESkhiJ11xBQOUlNTz+2IinptKwc7nIEQ4pqI9bDYhV8mp7Y30VBJkn5kJ1YsZOINpyob0gkn1LPg3qY+L3ynVD2siJkpehjNPbHnUrjBFE8+NHeDjgNtirF9YgAVim6gH2NAZFVWlBf+CeTJDikmc0vSNHPt+HNNsZKVCRQx633vUhPnq+/2zCu11dwAw6zXU6+bht6YSzobhudVC/tCZvvTr0aXv29QtASLyyIPkG7SkCic7bjavgKJ7QD+idunsAhD6i3qV3jdHWymGux3GRr3z4xiqLWLttu7seDKQCt5ZAaYaKsMvA66bGrX83VJ8P027x4TGJm8PjCFAsVUgE8WxXMhm1Xf8iUBkg1t/LtpMFd0ZBlxIrdZuF1n3PliPSSLfPQx3NgGiCtzhLM46y+UFgUL2RII+2iMXw+xDRQgxGwsSzxQ2n0skYiIgNtCBY8+SGhHAApxNuoK73K7/9g9+VPLOpLRuvhODuPwX7wooMUUshsgABNbfDRk/Z6vY0AuQTLSeb6Fitgpoig7IIx3EO5dUoenEChZS6cZ9E7buPfJQBZtTw/QokIhdx1IZatYf/JBAD2EzBEjJzHzj+7QGH5iiecLK99HXtOi3OFA=
